// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvzYBRPpo015NsFOhSGRPJnBgyBzN-hrg',
    appId: '1:190616309995:web:63704f284bba3be34c6eae',
    messagingSenderId: '190616309995',
    projectId: 'inksoul-b422c',
    authDomain: 'inksoul-b422c.firebaseapp.com',
    storageBucket: 'inksoul-b422c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2PQbG_EkneilwPVLezr-h3HuK8sqDmN4',
    appId: '1:190616309995:android:9fecd9616ff35b014c6eae',
    messagingSenderId: '190616309995',
    projectId: 'inksoul-b422c',
    storageBucket: 'inksoul-b422c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84ZpEoywByx2ZxQIv9OdPdP9blwDmu-g',
    appId: '1:190616309995:ios:5456f8a6140ec6c34c6eae',
    messagingSenderId: '190616309995',
    projectId: 'inksoul-b422c',
    storageBucket: 'inksoul-b422c.firebasestorage.app',
    iosBundleId: 'com.example.inksoul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC84ZpEoywByx2ZxQIv9OdPdP9blwDmu-g',
    appId: '1:190616309995:ios:5456f8a6140ec6c34c6eae',
    messagingSenderId: '190616309995',
    projectId: 'inksoul-b422c',
    storageBucket: 'inksoul-b422c.firebasestorage.app',
    iosBundleId: 'com.example.inksoul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvzYBRPpo015NsFOhSGRPJnBgyBzN-hrg',
    appId: '1:190616309995:web:b49136a3cdb893c04c6eae',
    messagingSenderId: '190616309995',
    projectId: 'inksoul-b422c',
    authDomain: 'inksoul-b422c.firebaseapp.com',
    storageBucket: 'inksoul-b422c.firebasestorage.app',
  );
}
